"use client";

import { useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ExternalLinkIcon, PackageIcon, SaveIcon } from "lucide-react";

import { FormActions, FormGrid, FormSection } from "@/components/admin/admin-form";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { EmptyState } from "@/components/shared/empty-state";
import { Button } from "@/components/ui/button";
import { Field, FieldContent, FieldDescription, FieldError, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "@/components/ui/toast";
import { PRODUCT_CATEGORIES } from "@/constants/domain";
import { cloneProduct, createEmptyProduct, slugify, validateProduct, type ProductDraft } from "@/lib/admin-content";
import { ProductImageManager } from "./content-image-manager";
import { useAdminContent } from "./content-provider";
import { VariantEditor } from "./variant-editor";

const categoryItems = PRODUCT_CATEGORIES.map((value) => ({ value, label: value }));

function ProductForm({ productId }: { productId: string }) {
  const router = useRouter(); const { products, addProduct, updateProduct } = useAdminContent();
  const isNew = productId === "nuevo"; const existing = products.find((product) => product.id === productId);
  const [draft, setDraft] = useState<ProductDraft>(() => isNew ? createEmptyProduct() : existing ? cloneProduct(existing) : createEmptyProduct());
  const [errors, setErrors] = useState<Record<string, string>>({}); const [slugEdited, setSlugEdited] = useState(!isNew); const [saving, setSaving] = useState(false);
  if (!isNew && !existing) return <EmptyState icon={PackageIcon} titleAs="h1" title="Producto no encontrado" description="El identificador no corresponde a un producto disponible en esta sesión." action={<Button render={<Link href="/admin/productos" />} nativeButton={false}>Volver a productos</Button>} />;
  const setValue = <K extends keyof ProductDraft>(key: K, value: ProductDraft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const setName = (name: string) => setDraft((current) => ({ ...current, name, slug: slugEdited ? current.slug : slugify(name) }));
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const nextErrors = validateProduct(draft); setErrors(nextErrors); if (Object.keys(nextErrors).length) { document.getElementById("product-form-errors")?.focus(); return; } setSaving(true); const saved = isNew ? addProduct(draft) : updateProduct(productId, draft); setSaving(false); if (!saved) return; toast.add({ title: isNew ? "Producto creado correctamente" : "Producto actualizado correctamente", description: `${saved.name} · cambios guardados en estado local.`, type: "success" }); if (isNew) router.replace(`/admin/productos/${saved.id}`); }
  return <div className="flex flex-col gap-5"><AdminPageHeader title={isNew ? "Agregar producto" : "Editar producto"} description={isNew ? "Creá una ficha para el catálogo del club." : existing!.name} breadcrumbs={[{ label: "Productos", href: "/admin/productos" }, { label: isNew ? "Nuevo" : existing!.name }]} actions={<>{!isNew && draft.isVisible ? <Button variant="outline" render={<Link href={`/tienda/${draft.slug}`} />} nativeButton={false}><ExternalLinkIcon data-icon="inline-start" aria-hidden="true" />Ver en sitio</Button> : null}<Button type="submit" form="product-form" disabled={saving}><SaveIcon data-icon="inline-start" aria-hidden="true" />{saving ? "Guardando…" : isNew ? "Agregar producto" : "Guardar cambios"}</Button></>} />
    <form id="product-form" onSubmit={submit} noValidate className="grid gap-4 xl:grid-cols-12"><div className="flex flex-col gap-4 xl:col-span-8">{Object.keys(errors).length ? <div id="product-form-errors" role="alert" tabIndex={-1} className="rounded-md border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive"><p className="font-semibold">Revisá los campos indicados.</p><p className="mt-1">Hay {Object.keys(errors).length} datos pendientes antes de guardar.</p></div> : null}
      <FormSection title="Información general" description="Datos compartidos por el panel, el catálogo y el detalle público."><FieldGroup><FormGrid><Field data-invalid={!!errors.name}><FieldLabel htmlFor="product-name">Nombre</FieldLabel><Input id="product-name" required value={draft.name} onChange={(event) => setName(event.target.value)} aria-invalid={!!errors.name} aria-describedby={errors.name ? "product-name-error" : undefined} />{errors.name ? <FieldError id="product-name-error">{errors.name}</FieldError> : null}</Field><Field data-invalid={!!errors.slug}><FieldLabel htmlFor="product-slug">Slug</FieldLabel><Input id="product-slug" required value={draft.slug} onChange={(event) => { setSlugEdited(true); setValue("slug", slugify(event.target.value)); }} aria-invalid={!!errors.slug} aria-describedby={errors.slug ? "product-slug-error" : "product-slug-help"} /><FieldDescription id="product-slug-help">/tienda/{draft.slug || "slug-del-producto"}</FieldDescription>{errors.slug ? <FieldError id="product-slug-error">{errors.slug}</FieldError> : null}</Field><Field className="md:col-span-2" data-invalid={!!errors.description}><FieldLabel htmlFor="product-description">Descripción</FieldLabel><Textarea id="product-description" required value={draft.description} onChange={(event) => setValue("description", event.target.value)} aria-invalid={!!errors.description} aria-describedby={errors.description ? "product-description-error" : undefined} />{errors.description ? <FieldError id="product-description-error">{errors.description}</FieldError> : null}</Field></FormGrid></FieldGroup></FormSection>
      <FormSection title="Imágenes" description="Galería local reutilizada del patrón de Canchas, sin storage real."><ProductImageManager images={draft.images} label={draft.name} onChange={(images) => setValue("images", images)} />{errors.images ? <FieldError className="mt-3">{errors.images}</FieldError> : null}</FormSection>
      <FormSection title="Variantes" description="Opciones simples como talle o color, con disponibilidad independiente."><VariantEditor variants={draft.variants} onChange={(variants) => setValue("variants", variants)} />{errors.variants ? <FieldError className="mt-3">{errors.variants}</FieldError> : null}</FormSection>
    </div><div className="flex flex-col gap-4 xl:col-span-4"><FormSection title="Precio y categoría"><FieldGroup><Field data-invalid={!!errors.price}><FieldLabel htmlFor="product-price">Precio de venta</FieldLabel><Input id="product-price" type="number" min="1" step="100" inputMode="numeric" required value={draft.price} onChange={(event) => setValue("price", Number(event.target.value))} aria-invalid={!!errors.price} aria-describedby={errors.price ? "product-price-error" : "product-price-help"} /><FieldDescription id="product-price-help">Importe en pesos argentinos.</FieldDescription>{errors.price ? <FieldError id="product-price-error">{errors.price}</FieldError> : null}</Field><Field data-invalid={!!errors.category}><FieldLabel htmlFor="product-category">Categoría</FieldLabel><Select items={categoryItems} value={draft.category || null} onValueChange={(value) => value && setValue("category", value)}><SelectTrigger id="product-category" aria-invalid={!!errors.category}><SelectValue>{(value) => value || "Seleccionar categoría"}</SelectValue></SelectTrigger><SelectContent><SelectGroup>{categoryItems.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectGroup></SelectContent></Select>{errors.category ? <FieldError>{errors.category}</FieldError> : null}</Field></FieldGroup></FormSection>
      <FormSection title="Publicación y disponibilidad" description="Cada control tiene una responsabilidad distinta."><FieldGroup><Field orientation="horizontal"><Switch id="product-available" aria-label="Disponible" checked={draft.isAvailable} onCheckedChange={(checked) => setValue("isAvailable", checked)} /><FieldContent><FieldLabel htmlFor="product-available">Disponible</FieldLabel><FieldDescription>Indica si el producto puede consultarse actualmente.</FieldDescription></FieldContent></Field><Field orientation="horizontal"><Switch id="product-visible" aria-label="Visible" checked={draft.isVisible} onCheckedChange={(checked) => setValue("isVisible", checked)} /><FieldContent><FieldLabel htmlFor="product-visible">Visible</FieldLabel><FieldDescription>Controla si aparece en la tienda pública.</FieldDescription></FieldContent></Field><Field orientation="horizontal"><Switch id="product-featured" aria-label="Destacado" checked={draft.isFeatured} onCheckedChange={(checked) => setValue("isFeatured", checked)} /><FieldContent><FieldLabel htmlFor="product-featured">Destacado</FieldLabel><FieldDescription>Permite mostrarlo en la Home si también está visible.</FieldDescription></FieldContent></Field></FieldGroup></FormSection></div>
      <div className="xl:col-span-12"><FormActions><Button variant="outline" render={<Link href="/admin/productos" />} nativeButton={false}>Volver</Button><Button type="submit" disabled={saving}><SaveIcon data-icon="inline-start" aria-hidden="true" />{saving ? "Guardando…" : isNew ? "Agregar producto" : "Guardar cambios"}</Button></FormActions></div></form></div>;
}

export { ProductForm };
